---
config:
  layout: elk
---
erDiagram
  Search {
    uuid id
    uuid taxon_concept_id
    uuid taxon_name_id
    string scientific_name
    string according_to
    string status
    date start_date
    date end_date
    string rank
    string kingdom
    string phylum
    string class
    string order
    string family
    string genus
    string species
    string specific_epithet
    string infraspecific_epithet
    jsonb mappings
  }