---
config:
  layout: elk
---
erDiagram
  %% Sidecars
  TaxonName |o--|| ScientificName_EXT : "taxonName / scientificName"

  %% Typification
  ScientificName_EXT |o--|{ NomenclaturalType : "typifiedName / typification"

  %% Scientific Name authorship
  ScientificName_EXT |o--|{ ScientificName_Author_MAP : scientificName
  ScientificName_Author_MAP }|--o{ Agent : agent
  ScientificName_EXT |o--|| Protologue_EXT : "publishedIn"
  Protologue_EXT ||--o| Reference : "reference / protologue"
  ScientificName_EXT }o--o| Reference : "publishedIn"

  TaxonName |o--|| VernacularName_EXT : "taxonName / vernacularName"

  %% The Syntactic Relationships
  ScientificName_EXT |o--|{ NameRelation_MAP : "fromName"
  ScientificName_EXT |o--|{ NameRelation_MAP : "toName"

  %% Taxon Name <--> Taxon Concept relationships
  TaxonName |o--|{ TaxonConcept : "taxonName"
  ScientificName_EXT |o--o{ TaxonConcept : "acceptedName"
  ScientificName_EXT }|--o| TaxonConcept : "synonyms"
  VernacularName_EXT }|--o| TaxonConcept : "vernacularNames"
  VernacularName_EXT }|--o| TaxonConcept : "preferredVernacularName"

  TaxonName |o--|| HybridFormula_EXT : "taxonName / hybridFormula"
  TaxonName |o--||  HybridFormula_EXT : "firstHybridParentName"
  TaxonName |o--|{ HybridFormula_EXT : "secondHybridParentName"

  TaxonName |o--|| InformalName_EXT : "taxonName / horticulturalGroupName"

  TaxonName |o--|| TaxonConceptLabel_EXT : "taxonName / taxonConceptLabel"

  %% Taxon Concept Label
  TaxonConceptLabel_EXT ||--o| TaxonConcept : "label"
  TaxonName |o--|{ TaxonConceptLabel_EXT : baseName

  %% External identifiers
  TaxonName |o--|{ Entity_Identity_MAP : "morphs as 'entity'"
  Entity_Identity_MAP }|--o| ExternalIdentity : "externalIdentity"

  TaxonName {
    int id PK
    int rank_id FK "nullable"
    string name_string
  }

  ScientificName_EXT {
    int id PK
    string authorship "nullable"
    int name_published_in_id FK "nullable"
    string name_published_in FK "nullable"
    string micro_reference FK "nullable"
    string year "nullable"
    int nomenclatural_code_id FK "nullable"
    int nomenclatural_status_id FK "nullable"
  }

  VernacularName_EXT {
    int id PK
    string language "nullable"
  }

  TaxonConceptLabel_EXT {
    int id PK
    int taxon_concept_id FK
    int base_name_id FK
  }

  HybridFormula_EXT {
    int id PK
    int first_hybrid_parent_name_id FK
    int second_hybrid_parent_name_id FK
  }

  InformalName_EXT {
    int id PK
  }

  NameRelation_MAP {
    int id PK
    int from_taxon_name_id FK
    int to_taxon_name_id FK
    int name_relation_type_id FK
    int reference_id FK "nullable"
    string remarks "nullable"
  }

  ScientificName_Author_MAP {
    int id PK
    int scientific_name_id FK
    int agent_id FK
    int author_role_id FK
    int sequence 
  }