---
config:
  layout: elk
---
erDiagram
  ExternalIdentity }|--|| ExternalIdentityAuthority_EXT : "externalIdentityAuthority"
  ExternalIdentityAuthority_EXT ||--o| Reference : "reference / externalIdentityAuthority"

  ExternalIdentity ||--|{ Entity_Identity_MAP : "externalIdentity"

  Entity_Identity_MAP }o--o{ TaxonConcept : "morphs as 'linkable'"
  Entity_Identity_MAP }o--o{ TaxonName : "morphs as 'linkable'"
  Entity_Identity_MAP }o--o{ Agent : "morphs as 'linkable'"

  ExternalIdentity {
    int id PK
    int source_system_id FK 
    string external_id
    string external_uri
    timestamp last_synced_at
  }

  Entity_Identity_MAP {
    int id PK
    string entity_type
    int entity_id
    int external_identity_id
  }