---
config:
  layout: elk
---
erDiagram
  Profile |o--|{ Profile_Specimen_MAP : "profile"
  Profile_Specimen_MAP }o--|| Specimen : "specimen"
  Specimen |o--|{ Entity_Identity_MAP : "morphs as 'linkable'"
  Entity_Identity_MAP }|--o| ExternalIdentity : "externalIdentity"
  Specimen |o--|{ Entity_Source_MAP : "morphs as 'provenanceable'"
  Entity_Source_MAP }|--o| Reference : "reference"
  Specimen |o--|{ Entity_Image_MAP : "morphs as 'depictable'"
  Entity_Image_MAP }|--|| Image : "image"

  Profile_Specimen_MAP {
    int id PK
    int profile_id FK 
    int specimen_id FK
    enum voucher_type
    int sort_order "nullable"
  }

  Specimen {
    int id PK
    string institution_code "nullable"
    string collection_code "nullable"
    string catalog_number "nullable"
    jsonb metadata "nullable"
  }