---
config:
  layout: elk
---
erDiagram
  AuditLog }|--|| Agent : "performedBy"

  AuditLog {
    bigint id PK
    int agent_id FK
    int event_type_id FK
    string table_name 
    int record_id 
    jsonb old_values "nullable"
    jsonb new_values "nullable"
    text change_summary "nullable"
  }