---
config:
    layout: elk
---
erDiagram
  Glossary |o--|{ GlossaryTerm : glossary

  Glossary |o--|{ GlossaryTermCategory : glossary
  GlossaryTermCategory |o--o{ GlossaryTerm : category
  GlossaryTerm |o--|| GlossaryTermCategory : term

  GlossaryTerm |o--|{ Entity_Image_MAP : "morps as 'entity'"
  Entity_Image_MAP }|--o| Image : image

  GlossaryTerm |o--|{ GlossaryTermRelationship : term
  GlossaryTermRelationship }|--o| GlossaryTerm : relatedTerm
  GlossaryTermRelationship }|--o| ControlledTerm : relationshipType

  %% Polymorphic Targets
  GlossaryTermRelationship |o--|{ Glossary_Limitation_MAP  : "morphs as 'limitable'"
  GlossaryTerm |o--|{ Glossary_Limitation_MAP : "morphs as 'limitable'"

  Glossary_Limitation_MAP }|--|| Limitation : "limitation"
  

  Glossary {
    int id PK
    string name 
    text description
  }

  GlossaryTerm {
    int id PK
    int glossary_id FK
    int category_id FK "nullable"
    string definition
    string scope "nullable"
    bool is_discouraged
    string local_id "nullable"
    string language "nullable"
    string name_addendum "nullable"
  }

  GlossaryTermCategory {
    int id PK
    int glossary_id FK
    int term_id FK
    string name 
  }

  GlossaryTermRelationship {
    int id PK
    int glossary_id FK
    int term_id FK
    int related_term_id FK
    int relationship_type_id FK
    bool is_misaplied
    bool is_discouraged
  }

  Limitation {
    int id PK
    string name 
  }