---
config:
    layout: elk
---
erDiagram
  TaxonConcept |o--|| Profile : "taxonConcept / profile"

  %% Vouchers
  Profile |o--|{ Profile_Specimen_MAP : "profile"
  Profile_Specimen_MAP }|--o{ Specimen : "specimen"
  Specimen |o--o{ Entity_Image_MAP : "morphs as 'depictable'"

  %% Media
  Profile |o--o{ Entity_Image_MAP : "morphs as 'depictable'"
  ProfileSection |o--o{ Entity_Image_MAP : "morphs as 'depictable'"
  Entity_Image_MAP }o--o| Image : "image"

  %% Sections
  Profile |o--|{ ProfileSection : "profile"
  ProfileSection }|--|| ProfileDefItem : "profileDefItem"

  %% References
  Profile |o--|{ Profile_Reference_MAP : "profile"
  Profile_Reference_MAP }|--o| Reference : "reference"

  %% Profile }o--o| Entity_Source_MAP : "morphs as 'provenanceable'"
  %% ProfileSection }o--|| Entity_Source_MAP : "morphs as 'provenanceable'"
  %% Entity_Source_MAP }|--o| Reference : "reference"
  %% Profile ||--|| Treatment_EXT : "treatment / profile"
  %% Treatment_EXT ||--o{ Reference : "reference / treatment" 
  %% Profile ||--|{ TreatmentVersion_EXT : "profile / treatmentVersions"
  %% TreatmentVersion_EXT ||--o{ Reference : "reference / treatmentVersion"
  %% Specimen |o--o{ Entity_Source_MAP : "morphs as 'provenanceable'"

  %% Distribution
  Profile |o--|{ Profile_Area_MAP : "profile"
  Profile_Area_MAP }|--o| AreaCode : "areaCode"
  AreaCode }|--o| Area : "area"

  Profile {
    int taxon_concept_id PK
    int taxon_tree_id FK
  }

  ProfileDefItem {
    int id PK
    int taxontree_id FK
    enum profile_section_type
    bool is_required
    int sort_order
  }

  ProfileSection {
    int id PK
    int profile_id FK
    int taxon_tree_id FK
    int profile_def_item_id FK
    text body_text
    int sort_order "nullable"
  }

  Profile_Reference_MAP {
    int id PK
    int profile_id FK
    int reference_id FK
  }