---
config:
  layout: elk
---
erDiagram
  Image |o--|{ Entity_Image_MAP : "image"

  Entity_Image_MAP }o--|| Profile : "morphs as 'depictable'"
  Entity_Image_MAP }o--|| ProfileSection : "morphs as 'depictable'"
  Entity_Image_MAP }o--|| Specimen : "morphs as 'depictable'"
  Entity_Image_MAP }o--|| GlossaryTerm : "morphs as 'depictable'"

  Image |o--|{ ImageCaption : "image"

  Image |o--|{ ImageAccessPoint : "image"

  Entity_Image_MAP {
    int id PK
    string entity_type
    int entity_id
    int image_id FK
    enum image_role
    int sort_order
  }

  Image {
    int id PK
    string uri
    enum image_type
    string scientific_name "nullable"
    string creator
    string rights_holder "nullable"
    string license "nullable"
    jsonb metadata "nullable"
  }

  ImageCaption {
    int id PK
    int image_id FK
    int taxon_tree_id FK
    text caption_body 
    text formatted_caption
  }

  ImageAccessPoint {
    int id PK
    int image_id FK
    enum variant
    string format
    int width
    int height
  }